pub fn for_locale(locale: &str) -> &'static [&'static str] {
    match locale {
        "de-DE" => DE,
        _ => EN,
    }
}

pub fn comma_separated(locale: &str) -> String {
    for_locale(locale).join(", ")
}

const EN: &[&str] = &[
    "Backend Developer",
    "DevOps Engineer",
    "Full Stack Developer",
    "Software Engineer",
    "API Development",
    "Microservices",
    "REST API",
    "GraphQL",
    "gRPC",
    "Node.js",
    "TypeScript",
    "JavaScript",
    "Python",
    "Go",
    "Rust",
    "Docker",
    "Kubernetes",
    "Helm",
    "Terraform",
    "Ansible",
    "AWS",
    "Azure",
    "Google Cloud",
    "DigitalOcean",
    "Vercel",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "MySQL",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "ArgoCD",
    "Monitoring",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Observability",
    "Load Balancing",
    "Nginx",
    "Traefik",
    "Service Mesh",
    "Istio",
    "Agile",
    "Scrum",
    "Clean Architecture",
    "TDD",
    "DDD",
    "Cloud Native",
    "Infrastructure as Code",
    "GitOps",
    "Software Developer",
    "Freelancer",
    "Remote Developer",
    "Cloud Consultant",
];

const DE: &[&str] = &[
    "Backend Entwickler",
    "DevOps Engineer",
    "Full Stack Developer",
    "Software Engineer",
    "API Entwicklung",
    "Microservices",
    "REST API",
    "GraphQL",
    "gRPC",
    "Node.js",
    "TypeScript",
    "JavaScript",
    "Python",
    "Go",
    "Rust",
    "Docker",
    "Kubernetes",
    "Helm",
    "Terraform",
    "Ansible",
    "AWS",
    "Azure",
    "Google Cloud",
    "DigitalOcean",
    "Vercel",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "MySQL",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "ArgoCD",
    "Monitoring",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Observability",
    "Load Balancing",
    "Nginx",
    "Traefik",
    "Service Mesh",
    "Istio",
    "Agile",
    "Scrum",
    "Clean Architecture",
    "TDD",
    "DDD",
    "Cloud Native",
    "Infrastructure as Code",
    "GitOps",
    "Software Entwickler",
    "Freelancer",
    "Remote Developer",
    "Cloud Consultant",
];
